
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author SC6966
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("Department");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 114, 150, 32);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("Doctor name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 66, 150, 30);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setText("Availability");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(41, 263, 150, 24);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setText("Timings");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(41, 323, 150, 24);

        jTextField1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(301, 18, 360, 30);

        jTextField2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(301, 68, 360, 26);

        jTextField3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(301, 115, 360, 30);

        jTextField4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(301, 164, 360, 30);

        jButton1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(41, 600, 144, 41);

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setText("Day");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 379, 150, 30);

        jComboBox1.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", " ", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(301, 379, 360, 30);

        jButton2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton2.setText("reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(301, 600, 133, 41);

        jButton3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(538, 600, 123, 41);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setText("CONTACT NUMBER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(41, 167, 150, 24);

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setText("DOCTOR ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(41, 21, 150, 24);

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel8.setText("SALARY");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(41, 215, 181, 24);

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(41, 471, 104, 24);

        jTextField5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(301, 212, 360, 30);

        jTextField6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(301, 260, 360, 30);

        jTextField7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(301, 320, 360, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(301, 442, 360, 96);

        jLabel10.setIcon(new javax.swing.ImageIcon("Z:\\hospital pics\\7.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-50, -40, 870, 740);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 790, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String docid=jTextField1.getText();   
String docname=jTextField2.getText(); 
String dept=jTextField3.getText(); 
String phone=jTextField4.getText();
Object day=jComboBox1.getSelectedItem();
String salary=jTextField5.getText(); 
String availability=jTextField6.getText(); 
String time=jTextField7.getText(); 
String address=jTextArea1.getText();
if(docid.isEmpty()) {
JOptionPane.showMessageDialog(this, "DOCTOR ID  Not Entered");
}

else if(docname.isEmpty())
{
JOptionPane.showMessageDialog(this, "DOCTOR NAME Not Entered");
}
        
else if(dept.isEmpty())
{
JOptionPane.showMessageDialog(this, "DEPARTMENT Not Entered");
}
         
else if(phone.isEmpty())
{
JOptionPane.showMessageDialog(this, "PHONE NUMBER Not Entered");
}

else      
{ 
    try 
        {
           Class.forName("java.sql.DriverManager");
           Connection con = (Connection)
           DriverManager.getConnection("jdbc:mysql://localhost:3306/classproject","root","Ak47");
           Statement stmt=(Statement) con.createStatement();
           String query = "INSERT INTO hospi VALUES('"+docid+"','"+docname+"','"+dept+"','"+phone+"','"+day+"','"+salary+"','"+availability+"','"+time+"','"+address+"');";
           stmt.executeUpdate(query);
              
           JOptionPane.showMessageDialog(this, "Added a New Data");
               
         }
                    
    catch(Exception e)
    {
          
           JOptionPane.showMessageDialog(this, e.getMessage());}

          }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText(" ");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextArea1.setText("");
jComboBox1.setSelectedIndex(0);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
