
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sc6966
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 100, 208, 30);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("ENTER YOUR FULL NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 110, 204, 20);

        jTextField2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(500, 170, 208, 30);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("PHONE NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 170, 129, 20);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setText("E-MAIL ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 240, 65, 20);

        jTextField3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(500, 230, 208, 30);

        jButton1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton1.setText("SEND REQUEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 390, 157, 30);

        jButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 390, 73, 30);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setText("DOCTOR ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 290, 86, 20);

        jTextField4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(500, 290, 208, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel5.setText("To get an APPOINTMENT......");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 40, 320, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc6966\\Desktop\\4.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-160, -60, 1170, 660);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(730, 40, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name=jTextField1.getText();   
String phone=jTextField2.getText(); 
String email=jTextField3.getText(); 
String docid=jTextField4.getText(); 


if(name.isEmpty()) 
{
JOptionPane.showMessageDialog(this, "NAME Not Entered");
}

else if(phone.isEmpty()) 
{
JOptionPane.showMessageDialog(this, "PHONE Not Entered");
}
         
else if(email.isEmpty()) {
JOptionPane.showMessageDialog(this, "EMAIL Not Entered");
}

else if(email.isEmpty()) {
JOptionPane.showMessageDialog(this, "DOCTOR ID Not Entered");
}
        
else      

{ 
    try 
{
                      
Class.forName("java.sql.DriverManager");
Connection con = (Connection)
DriverManager.getConnection("jdbc:mysql://localhost:3306/classproject","root","1234");
Statement stmt=(Statement) con.createStatement();
String query = "INSERT INTO appointment VALUES('"+name+"','"+phone+"','"+email+"','"+docid+"');";
stmt.executeUpdate(query);
JOptionPane.showMessageDialog(this, " APPOINTMENT REQUEST SENT ");

String query1 ="Select count(docid) from appointment where docid='"+docid+"' having count(docid) <= 6; ";
       
       ResultSet rs =stmt.executeQuery(query1); 
       if(rs.next())
             { 
            String  count=rs.getString("count(docid)"); 
            jTextField5.setText(count); 
             
       int x=Integer.parseInt(jTextField5.getText());
       if (x<=6)
           JOptionPane.showMessageDialog(null, " YOUR APPOINTMENT HAS BEEN APPROVED PLEASE BE ON TIME ");
       else
           JOptionPane.showMessageDialog(null, " SORRY !!! YOUR APPOINTMENT CAN'T BE ACCEPTED CHECK FOR ANOTHER DOCTOR ");
             }
           
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this, e.getMessage());
}
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
