
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SC6966
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 4, 1));
        jLabel1.setText("Department");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 59, 200, 33);

        jTextField1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 29, 45));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(366, 56, 270, 30);

        jButton1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(21, 1, 36));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 190, 390, 50);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 4, 1));
        jLabel3.setText("Day");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 114, 148, 33);

        jComboBox1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 29, 45));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(366, 111, 270, 30);

        jButton2.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(21, 1, 36));
        jButton2.setText(".APPOINTMENT   REQUEST.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 560, 700, 50);

        jButton3.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(21, 1, 36));
        jButton3.setText("EXIT");
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 620, 320, 50);

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 4, 1));
        jLabel2.setText("Timings");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 300, 160, 40);

        jTextField2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 29, 45));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 310, 290, 30);

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 4, 1));
        jLabel4.setText("Doctor Available");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 360, 250, 43);

        jTextField4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 29, 45));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(370, 366, 290, 30);

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 4, 1));
        jLabel6.setText("DOCTOR ID ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 429, 260, 33);

        jTextField3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 29, 45));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(370, 421, 290, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel5.setText("// Please remember the doctor ID for the next form ..");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 490, 730, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a7.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(750, 0, 150, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a8.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-60, 0, 960, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String dept = jTextField1.getText();

        if (dept.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter department");
        } else {
            String day = null;

            switch (jComboBox1.getSelectedIndex()) {
                case 0:
                    day = "Sunday";
                    break;
                case 1:
                    day = "Monday";
                    break;
                case 2:
                    day = "Tuesday";
                    break;
                case 3:
                    day = "Wednesday";
                    break;
                case 4:
                    day = "Thursday";
                    break;
                case 5:
                    day = "Friday";
                    break;
                case 6:
                    day = "Saturday";
                    break;
            }

            try {
                String url = "jdbc:mysql://localhost:3306/classproject";
                String username = "root";
                String password = "Ak47";

                // Use try-with-resources to automatically close resources
                try (Connection con = DriverManager.getConnection(url, username, password);
                     PreparedStatement stmt = con.prepareStatement("SELECT docname, time, docid FROM hospi WHERE dept=? AND day=?")) {

                    stmt.setString(1, dept);
                    stmt.setString(2, day);

                    // Execute the query
                    try (ResultSet rs = stmt.executeQuery()) {
                        if (rs.next()) {
                            String docname = rs.getString("docname");
                            String time = rs.getString("time");
                            String docid = rs.getString("docid");

                            // Update your JTextField fields
                            jTextField4.setText(docname);
                            jTextField2.setText(time);
                            jTextField3.setText(docid);
                        } else {
                            JOptionPane.showMessageDialog(this, "No records found for the given department and day");
                        }
                    }
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "SQL error: " + e.getMessage());
            } 
        }


             
             
                    
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
new Appointment().setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
